version: '3.4'

services:
  graphqlserver:
    image: ${DOCKER_REGISTRY-}graphqlserver
    build:
      context: .
      dockerfile: GraphQLServer/Dockerfile
    ports:
     - "8080:80"
     - "54321:443"
    environment:
      ConnectionStrings_DefaultConnections: "Host=postgres;Database=postgres;UserName=postgres;Password=postgres;"
    depends_on:
     - "postgres"
    networks:
      - graphqlserver-network

  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - graphqlserver-network

networks:
  graphqlserver-network:
    driver: bridge